name: 'organizer'

volumes:
  postgres-data:

networks:
  postgres-network:
    driver: bridge

services:
  postgresql:
    container_name: organizerdb
    image: 'postgres:15'
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: 'GMT+3'
      PGTZ: 'GMT+3'
    restart: unless-stopped
    volumes:
      # - ./database/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - postgres-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - postgres-network
